# Generated by Django 5.2.4 on 2025-09-12 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_variation'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='Variation_value',
            field=models.CharField(default='Standard Variation', max_length=100),
        ),
    ]
