# Generated by Django 5.2.4 on 2025-09-12 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_variation_variation_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='Variation_value',
            field=models.CharField(default='', max_length=100),
        ),
    ]
