# Generated by Django 5.2.4 on 2025-09-13 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_variation_variation_value_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variation',
            old_name='Variation_value',
            new_name='variation_value',
        ),
    ]
