# Generated by Django 5.2.5 on 2025-08-21 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='quwantity',
            new_name='quantity',
        ),
    ]
