# Generated by Django 5.2.4 on 2025-09-13 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_rename_quwantity_cartitem_quantity'),
        ('store', '0006_alter_variation_variation_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='variation',
            field=models.ManyToManyField(blank=True, to='store.variation'),
        ),
    ]
